### ISSUE TITLE
Support IEnumerable<IWebElement> for cases where parent is not easily located

### ISSUE THREAD

**Issue by jonstelly** [dpiessens/specbind#100]
I'm using Selenium and have HTML like the following:

````
<div>
  <div class="projectCard">...</div>
  <div class="projectCard">...</div>
  <div class="projectCard">...</div>
  <div class="projectCard">...</div>
</div>
````

I'd like to simply set up a page like this:

````
public class HomePage
{
  [ElementLocator(Class="projectCard")]
  public IEnumerable<ProjectCard> Projects {get; set;}
}

public class ProjectCard
{
}
````

But this doesn't appear to be possible from what I can see in documentation and looking at the code.  First off, am I correct that this isn't possible today?

If it's not, would something like this be accepted in a pull request?  Can someone spend a couple minutes and point me in the right direction here?  There are a few ways to implement this, a new Attribute like ElementLocator, just infer what we're trying to do if the property type is an IEnumerable<T> but not an IElementList<T>...

Thoughts?

**Comment by NickMcG** [comment]
Is it possible to modify the markup? I think this could be easily solved if you had a way to uniquely identify the parent. If you could slap a class or id on the parent element, then this just becomes a standard list (see https://github.com/dpiessens/specbind/wiki/Working-With-Lists).

**Comment by dpiessens** [comment]
It's pretty difficult for any of the UI automation frameworks to locate a given number of elements with an undefined parent. The risk is that on complicated pages it may grab unrelated items and it takes a lot of DOM searching to make sure they all have the same parent element which takes time. 

The right way to do this is to identify that parent div tag, I'll keep this open as a future enhancement if it's something you want to work on.

**Comment by jonstelly** [comment]
I can add an id to the parent, but I had pretty drastically simplified my example for the sake of creating this issue, but what I really have is:

````
<div>
  <div class="projectCard"/>
  <div class="legacyProjectCard"/>
  <div class="projectCard"/>
  <div class="legacyProjectCard"/>
</div>
````

It's slightly more complicated than that but essentially, we have a flag for our app being in legacy mode or not, and show/hide the appropriate cards.

I get the point about performance and I can add an id to the container, but I'd still like to split these two things up in my page structure:

````
public class HomePage
{
  [ElementLocator(Class="projectCard")]
  public IEnumerable<ProjectCard> Projects {get; set;}

  [ElementLocator(Class="legacyProjectCard")]
  public IEnumerable<LegacyProjectCard> LegacyProjects {get;set;}
}
````

The Project Cards and Legacy Project Cards have structure different enough that it would be ugly to have to define a single class to cover both.  So is a better discussion to talk about ways to filter child items inside an IEventList<T>?

**Comment by NickMcG** [comment]
Here is the approach I did to get this working: I had the collection root high up on the DOM tree (body, but you could go lower on the DOM if there is a better parent), then have the children be based off of the projectCard class name.

Page Models:

	[PageNavigation("/Home/TestView")]
	public class TestViewPage
	{
		[ElementLocator(TagName = "body")]
		public IElementList<IWebElement, ProjectCard> ProjectCards { get; set; }
	}

	[ElementLocator(Class = "projectCard")]
	public class ProjectCard : WebElement
	{
		public ProjectCard(ISearchContext searchContext) : base(searchContext)
		{
		}

		[ElementLocator(Class = "name")]
		public IWebElement Name { get; set; }

		[ElementLocator(Class = "description")]
		public IWebElement Description { get; set; }
	}


Gherkin:
`Scenario: Testing things
	When I navigate to the test view page
	Then I see the project cards list contains exactly 4 items
`

**Comment by jonstelly** [comment]
Ahhh, that's great.  I didn't see that ElementLocator could be applied to the Child class to filter like that.  Thanks a ton.

Would you guys like me to submit a pull request to add an example of this to the Wiki page for [Working With Lists](https://github.com/dpiessens/specbind/wiki/Working-With-Lists)?  Would you call that something like Child Element Filtering?

**Comment by dpiessens** [comment]
@NickMcG That's a great setup, good call! @jonstelly If you'd like to submit a PR for documentation that would be wonderful. There's definitely a need for that to get more verbose at some point.
