### ISSUE TITLE
SpecBindGeneratorPlugin.SpecFlow requires SpecFlow 1.9, but SpecBind uses 2.0

### ISSUE THREAD

**Issue by adback03** [dpiessens/specbind#101]
I noticed that SpecBind got updated to use SpecFlow v2.0, but a new SpecBindGeneratorPlugin.SpecFlow plugin was never pushed out that also uses SpecFlow 2.0 (it still uses 1.9). So if you try updating NuGet references for SpecBind, SpecBindGeneratorPlugin.SpecFlow, and SpecFlow, you get the following error:

![capture](https://cloud.githubusercontent.com/assets/3609623/13958568/8ed9a920-f01e-11e5-8717-ab6957d8dcf7.PNG)

**Comment by dpiessens** [comment]
Yeah, somehow that got updated before I wanted to push out. I'm building 1.7.0 right now and that should have all the updates.

**Comment by adback03** [comment]
Cool, thanks!

**Comment by dpiessens** [comment]
OK 1.7.0 is released, that should work now.
