### ISSUE TITLE
Maximising the browser window is not supported on Android/Browserstack

### ISSUE THREAD

**Issue by scottcowan** [dpiessens/specbind#109]
I would like the option to toggle whether or not maximize is called on the webdriver
because the webdriver for Android 4.4/5.0 on browser stack does not support this

```
unknown error: operation is unsupported on Android (Session info: webview=30.0.0.0) (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64)
```

[SeleniumBrowserFactory.cs:116](https://github.com/dpiessens/specbind/blob/0c213e12ddb528d593fabd079a1db445c8c36b25/src/SpecBind.Selenium/SeleniumBrowserFactory.cs#L116)

``` csharp
// Maximize window
managementSettings.Window.Maximize();
```

**Comment by icnocop** [comment]
I noticed the Android browser type was removed in SpecBind 2.0.

I'm not exactly sure how to run tests against the Android browser using SpecBind 2.0 or how it affects the call to maximize the browser window.

@dpiessens, any ideas?

Thank you!

**Comment by dpiessens** [comment]
The browser type was removed because Selemium deprecated the driver and was throwing warnings to remove the browser type. I'm not sure what their recommended approach is for mobile testing going forward, but given we con't support the browser I'm closing the issue.
