### ISSUE TITLE
`@Highlight` tag is not documented

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#113]
The `@Highlight` tag is not documented.

The only reference is in issue https://github.com/dpiessens/specbind/issues/8 (and in the source code itself).

I expected there to be a help topic for SpecFlow tags that can be used for Coded UI tests in the [Documentation](https://github.com/dpiessens/specbind/wiki/Documentation) for example.

Thank you.

**Comment by dpiessens** [comment]
Added a debugging section to the documentation https://github.com/dpiessens/specbind/wiki/Debugging #
