### ISSUE TITLE
Waiting for angular and jQuery ajax calls steps and configuration setting is not documented.

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#114]
The new `waitForPendingAjaxCallsVia` configuration setting and steps are not documented.

I expected the new `waitForPendingAjaxCallsVia` configuration setting to be documented in https://github.com/dpiessens/specbind/wiki/Configuration.

I expected the new wait for steps to be documented in https://github.com/dpiessens/specbind/wiki/Waiting-Steps.

The only references are in pull request #103.

Thank you.

**Comment by dpiessens** [comment]
Added this to configuration and waiting steps.
