### ISSUE TITLE
browserstack.key stored outside of the app.config

### ISSUE THREAD

**Issue by scottcowan** [dpiessens/specbind#116]
I would like avoid storing my browserstack.key in the config file since I might accidentally commit it into our public repo.

Maybe we could check for an environment variable where these are stored in addition to the config file? this would be for running tests locally since we run a powershell to insert these on our nightly test runs.

**Comment by dpiessens** [comment]
Yeah and environment setting seems like a good way to manage that. Technically you could use app.config encryption to protect it since the key is on the target machine, but that's not as modular and let's face it, no one remembers how to do that encryption anyway :)

**Comment by dpiessens** [comment]
This is resolved in 1.7.3, add a value of ${MY_ENV_VAR} to the setting and it will then reference the environment variable.

**Comment by scottcowan** [comment]
Cheers dan
