### ISSUE TITLE
Fix typos in Debugging wiki

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#120]
I fixed a couple of typos in the Debugging wiki.

You can see my changes here:
https://github.com/icnocop/specbind-wiki/commit/5bce5a20fa8d81f77430b82ce5b17eff28319e49

Thank you.

**Comment by dpiessens** [comment]
Thanks,  would you mind trying to submit a pull request? I'm pretty sure it
works.

**Comment by icnocop** [comment]
I tried to create a pull request but it doesn't seem that I can.

My "specbind-wiki" repository is just a clone and not actually a fork of the specbind wiki; unfortunately, it seems github wikis cannot be forked and therefore I cannot create a pull request.

https://help.github.com/articles/about-github-wikis/
http://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github

**Comment by dpiessens** [comment]
No problem I fixed it from your code. Thanks!
