### ISSUE TITLE
Can't enter special characters intended for Keyboard.SendKeys

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#121]
It seems that I can't use special characters intended for Keyboard.SendKeys.

For example how do I enter a left curly bracket in an HTML text input control?
```
Scenario Outline: Entering special characters
 Given I navigated to the Home page
 And I entered data
        | Field        | Value         |
        | MyField      | <Value>       |

    Examples: 
      | Description          | Value |
      | Left Curly Brace     | {     |
      | Caret Symbol         | ^     |
      | Tilde                | ~     |
      | Plus Sign            | +     |
      | Percentage Sign      | %     |
```

According to https://msdn.microsoft.com/en-us/library/system.windows.forms.sendkeys.send.aspx I should be able to wrap them in a set of curly braces, but that didn't work either.

Any ideas?

Is it because the curly braces conflict with the Tokens feature?

Thank you!

**Comment by dpiessens** [comment]
Hi,

Yup, I never considered that MSTest uses that for special characters. I'll have to add escaping for the brackets and then see if it works with the driver.

Dan

**Comment by dpiessens** [comment]
This should be fixed in the next update, I'm adding it to the docs, but if you just double the braces `{{TAB}}` it will treat it as a literal.
