### ISSUE TITLE
'WaitToSeeElement' is not working as expected.

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#124]
Hi.

I'm trying to wait until an element with specific text exists on a page, but specbind doesn't seem to wait and acts as if the element exists.

How to reproduce:

Add the following to `.\specbind\src\SpecBind.CodedUI.IntegrationTests\Features\WaitingTests.feature`
```
Scenario: Wait for element
	Given I navigated to the Home page
	 And I chose New Information
	 And I was on the Information page
	When I choose Alert Box
	 And I see an alert box and select Ok
	Then I wait to see You Pressed Ok
```
Add the following to `.\specbind\src\SpecBind.CodedUI.IntegrationTests\Pages\InformationPage.cs`
```
        [ElementLocator(Text = "You pressed OK!")]
        public HtmlDiv YouPressedOk { get; set; }
```

Run the `WaitForElement` test and notice that the test passes without error.

This is unexpected because what is actually displayed on the page is "Alert Cleared" and "You Pressed OK!" is never displayed on the page.

("You Pressed OK!" is only displayed when the "Confirm Box" button is clicked, and not the "Alert Box".)

Any ideas?

Thank you!

**Comment by dpiessens** [comment]
Text locators are not primary locators on the page so it most likely responded to something else on the page existing. If you look at element location doc, Microsoft suggests not using text as a primary element locator.
