### ISSUE TITLE
Update SpecBind to support SpecFlow 2.1.0

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#125]
Hi.

SpecBind 1.7.3.280 doesn't support SpecFlow 2.1.0 because the [IGeneratorPlugin](https://github.com/techtalk/SpecFlow/blob/master/TechTalk.SpecFlow.Generator/Plugins/IGeneratorPlugin.cs) interface has changed.

After adding `<Import Project="..\packages\SpecFlow.2.1.0\tools\TechTalk.SpecFlow.targets" />` to the project file to support CI builds, the following error occurs:
`\packages\SpecFlow.2.1.0\tools\TechTalk.SpecFlow.targets(47,5): error : Method 'Initialize' in type 'SpecBind.Plugin.SpecBindGeneratorPlugin' from assembly 'SpecBindGeneratorPlugin.Generator.SpecflowPlugin, Version=1.7.3.280, Culture=neutral, PublicKeyToken=null' does not have an implementation.`

I'm thinking that future versions of SpecBind will only support SpecFlow 2.1+, so we'd have to also update SpecBind.nuspec accordingly.

Thank you.

**Comment by dpiessens** [comment]
Publishing as version 2.0.0.305 of SpecBind
