### ISSUE TITLE
Fix typo, formatting, and indicate rule key shouldn't contain spaces in wiki (pull request)

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#128]
I fixed a typo, formatting, and indicated the rule key shouldn't contain spaces in the wiki page "Custom-Validation-Rules.md".

Please see my repository here: https://github.com/icnocop/specbind-wiki

Thank you! :)

**Comment by dpiessens** [comment]
I made the update in the docs, thanks!
