### ISSUE TITLE
How to maintain same browser instance for different scenarios

### ISSUE THREAD

**Issue by Amjuri** [dpiessens/specbind#131]
I created two scenarios, Once the first scenario executed the second scenario is not executing the same browser instance. 
I have given "page Navigation" element for both the scenarios page classes. I Have tried using "given I navigated to Page" and Given I was on the page" for the second scenario.  But I see while executing the test. the second scenario is opening the new browser instance. 
I thought to control the browser instance using "beforescenario" hook, But I don't know how to get the browser instance in Specbind.

**Comment by icnocop** [comment]
Re-using the browser window between tests is not recommended.

Which driver are you using?

If Coded UI, see https://stackoverflow.com/questions/14426202/how-do-i-keep-the-browser-open-after-a-coded-ui-test-finishes

This issue may be related to https://github.com/dpiessens/specbind/issues/118 as you'd need access to the BrowserWindow instance.

**Comment by dpiessens** [comment]
I'd agree that you don't want to reuse instances. Is the use case that you want to create an item and then update it? There are setups you can do that will run a set of cases before each scenario so you can model it without repeating all the steps.

**Comment by Amjuri** [comment]
@icnocop  Thanks for your reply. I am creating the tests in Specbind-CodedUI.
@dpiessens, I want to reuse the browser instance for different scenarios. The Use case is, After executing the one scenario, the second scenario need to be executed on the same browser. Example: scenarios like login and then verify account details:  I  would need to execute these scenarios together by passing "page navigation" attribute. however, the problem here is, when it executes the second scenario, it opens new browser instance. 

I would like to know, if I could accomplish this within the same browser instance by any chance? so that I could combine multiple scenarios and execute in one flow.

**Comment by dpiessens** [comment]
The intent of the suite is to make tests non-deterministic. SpecFlow allows for examples so you can build on a suite so you shouldn't rely on not closing a test to make it function.
