### ISSUE TITLE
Wiki page "Page Navigation Binding" needs to be updated...

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#139]
Hi.

The wiki page, [Page Navigation Binding](https://github.com/dpiessens/specbind/wiki/Page-Navigation-Binding) has some issues:
1. It references Watin instead of Selenium:

> For Watin this is WatiN.Core.Page

2. There's a hyperlink for the "Linking Navigation section", but the link is incorrect.

> More on this in the Linking Navigation section.

Instead of
https://github.com/dpiessens/specbind/wiki/#Linking-Navigation#Linking-Navigation
It should be
https://github.com/dpiessens/specbind/wiki/Page-Navigation-Binding#linking-navigation
(Also, it's case sensitive)

Thank you.

**Comment by dpiessens** [comment]
Fixed, thanks for finding these
