### ISSUE TITLE
"Given/When/Then I wait(ed) for the X page" steps are not documented

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#142]
Hi.

The "Given/When/Then I wait(ed) for the X page" steps are not documented.

This includes the "Given/When/Then I wait(ed) X second(s) for the X page" steps.

I expected them to be documented in the [Waiting Steps](https://github.com/dpiessens/specbind/wiki/Waiting-Steps) wiki page.

For reference, see https://github.com/dpiessens/specbind/issues/72.

Thank you!

**Comment by dpiessens** [comment]
Added this to the Waiting Steps and Navigation steps pages.
