### ISSUE TITLE
Typo on the 'Page Model Properties Selenium' wiki page

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#149]
Hi.

There's a typo on the 'Page Model Properties Selenium' wiki page [here](https://github.com/dpiessens/specbind/wiki/Page-Model-Properties-Selenium).

The code `public class ProductsPage:HtmlDocument` should be `public class ProductsPage`.

Thank you.

**Comment by dpiessens** [comment]
Fixed thanks.
