### ISSUE TITLE
Missing `ElementLocator` attributes in code samples on "Working With Lists" wiki page

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#152]
Hi.

The wiki page [Working With Lists](https://github.com/dpiessens/specbind/wiki/Working-With-Lists) has missing `ElementLocator` attributes on the `ProductItemDiv` classes.

For example:
```
public class ProductItemDiv : HtmlDiv
```
should be:
```
[ElementLocator(Id = "productItem")]
public class ProductItemDiv : HtmlDiv
```

And 
```
public class ProductItemDiv : WebElement
```
should be:
```
[ElementLocator(Id = "productItem")]
public class ProductItemDiv : WebElement
```

Also

> The second type is a private class that represents which exposes properties of each individual list item.

Should probably be

> The second type is a class that represents and exposes properties of each individual list item.

Thank you.

**Comment by dpiessens** [comment]
Updated, thanks
