### ISSUE TITLE
Verb tables in the "Verifying Steps" wiki page indicate "When" steps but should be "Then"

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#154]
Hi.

The "Validating Fields", "Validating Lists", and "Validating List Counts" sections of the [Verifying Steps](https://github.com/dpiessens/specbind/wiki/Verifying-Steps) wiki page have tables like

| Verb | Action |
| -- | -- | 
| Given | I saw ... |
| When | I see ...|

But should be

| Verb | Action |
| -- | -- | 
| Given | I saw ... |
| Then | I see ...|

Because the `WhenAttribute` is not applied on those steps.

Or maybe the `WhenAttribute` should be applied to those steps and then the wiki page should just be updated to include the `Then` verbs?

Thank you.

**Comment by dpiessens** [comment]
I changed it to _Then_, you don't want to be doing validation doing the _When_ step, similar to the 3A pattern with unit tests.
