### ISSUE TITLE
Typos on "Waiting Steps" wiki page

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#161]
Hi.

I noticed a few typos on the [Waiting Steps](https://github.com/dpiessens/specbind/wiki/Waiting-Steps) wiki page.

They're all in the "Check to see if ajax calls are completed" section, at the very bottom.

1. I noticed there are 4 tables when there should only be 2.
2. All the `Given` steps should read `I waited for ...`
3. All the `When` and `Then` steps should read `I wait for ...`

Thank you.

**Comment by dpiessens** [comment]
Fixed.
