### ISSUE TITLE
PhantomJS and Opera are not indicated as supported browsers in the wiki

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#164]
PhantomJS and Opera are indicated as browser types in 
https://github.com/dpiessens/specbind/blob/master/src/SpecBind/BrowserSupport/BrowserType.cs

And in the Selenium browser factory
https://github.com/dpiessens/specbind/blob/master/src/SpecBind.Selenium/SeleniumBrowserFactory.cs

But they aren't indicated as supported browsers in the wiki at
https://github.com/dpiessens/specbind/wiki/Configuration#supported-browsers

Thank you.

**Comment by dpiessens** [comment]
Yup that's why I removed them from documentation. I got deprecation warnings in the code so I figured a soft removal by not putting it in the docs and then removing it when we go to 3.14.0 is better.
