### ISSUE TITLE
Out of place code example in documentation in `Waiting Steps` wiki page

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#167]
The wiki page https://github.com/dpiessens/specbind/wiki/Waiting-Steps has the following text:

> The example below shows waiting for Checkout to become enabled:
> 
> `Given I waited for Checkout to become enabled`
> 

Unfortunately, it's out of place.

It should probably appear right after the `Check to see if an element is enabled` section.

Thank you.

**Comment by dpiessens** [comment]
Fixed, thanks
