### ISSUE TITLE
Typo on the "Page Model Properties Selenium" wiki page

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#189]
Hi.

I found a typo on the [Page Model Properties Selenium](https://github.com/dpiessens/specbind/wiki/Page-Model-Properties-Selenium) wiki page.

It's in the last code example, in the `Accessing Element Attributes` section.

`[VirtualProperty(Attribute="href" Name="LogOnUrl")]`
should be
`[VirtualProperty(Attribute="href", Name="LogOnUrl")]`

Notice the missing comma.

Thank you.

**Comment by dpiessens** [comment]
Fixed thanks.
