### ISSUE TITLE
First-time setup: Can't open test in Chrome

### ISSUE THREAD

**Issue by p2635** [dpiessens/specbind#195]
It's my first time using this and I can't get this to work with Selenium. Is my config file correct?

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <configSections>
    <section name="specBind" type="SpecBind.Configuration.ConfigurationSectionHandler, SpecBind"/>
  </configSections>
  <specBind>
    <application startUrl="http://google.com/" />
    <browserFactory provider="SpecBind.Selenium" browserType="Chrome" />
  </specBind>
</configuration>
```

My scenario just says:
Given I navigated to the 'https://github.com/dpiessens/specbind/wiki/Navigation-Steps' page

**Comment by icnocop** [comment]
What error do you get?

It doesn't seem like you installed SpecFlow to the test project; I expected to also see a SpecFlow configuration in the config file.

The "Given I navigated to the X page" navigation step shouldn't have a URL in there.
It should be passed a "page name" as indicated in https://github.com/dpiessens/specbind/wiki/Navigation-Steps.
The "page name" should be mapped to a class.

**Comment by p2635** [comment]
Thanks @icnocop, there are no errors for some reason. Although I ran the test, nothing happens and it still says '1 not run test'. I created the app.config file from scratch as I could not see an existing SpecFlow config file.

These are the specflow related packages installed:
![image](https://user-images.githubusercontent.com/4522927/75242045-394dee00-57bf-11ea-9f10-6aa21bbbc3a7.png)

As for the link, I don't really mind what link I am using for the URL, I was just testing one of the specbind steps. I guess I can do '/dpiessens/specbind/wiki/Navigation-Steps' once I manage to set the base link correctly.

**Comment by icnocop** [comment]
Does your test project target .NET Framework or .NET Core?
Which version?

**Comment by icnocop** [comment]
It seems you have to target .NET Framework because SpecBind doesn't currently support SpecFlow 3.x.

SpecBind currently expects the type `BoDi.IObjectContainer` to exist in `TechTalk.SpecFlow.dll` but that's no longer the case in SpecFlow 3.x, and an error occurs when a test is run.

In order to reference SpecFlow 2.x, the test project needs to target .NET Framework 4.5+ because SpecFlow 2.x doesn't support .NET Core.

**Comment by p2635** [comment]
I see, if SpecBind doesn't support SpecFlow 3.x then I will not use it for now. It would be good if this could be written somewhere for anyone else who has the same problem. thanks @icnocop
