### ISSUE TITLE
Scenario titles in .\SpecBind.CodedUI.IntegrationTests\Features\DivListValidationTests.feature are not accurate

### ISSUE THREAD

**Issue by icnocop** [dpiessens/specbind#196]
The scenario titles in https://github.com/dpiessens/specbind/blob/master/src/SpecBind.CodedUI.IntegrationTests/Features/DivListValidationTests.feature are not accurate.

For example,
```
Scenario: Validate Div List "Start With" Validator
	  Then I see results grid list starts with
		   | Field           | Rule   | Value       |
		   | Department Name | Equals | Economics   |
		   | Budget          | Equals | $100,000.00 |
```

The title indicates we're testing the "Start[s] With" validator, but the validation table only has the "Equals" rule.

**Comment by dpiessens** [comment]
The "starts with" refers to the list, not the rules. This is a more complicated description as we have to determine what part of the list of items w're looking at and then how to determine if the item in the list is valid. So in this case we're checking if the first item in the list has a department name that equals economics and a budget that equals $100k.
