### ISSUE TITLE
The HTTP request to the remote WebDriver server timed out after 60 seconds

### ISSUE THREAD

**Issue by robertbird** [dpiessens/specbind#56]
Hi Dan,

This may not be an issue with SpecBind (which is great BTW!) and more of a problem with WebDriver and how we are using Selenium Grid, but I wondered if there was a setting somewhere that is not being applied.

I am running the tests on my CI build server which then connects to a remote webdriver server. 

My config looks like this:

    <specBind>
      <application startUrl="https://www.myurlgoeshere.com" />
      <browserFactory provider="SpecBind.Selenium.SeleniumBrowserFactory, SpecBind.Selenium" 
                    browserType="Chrome" 
                    elementLocateTimeout="00:01:30"
                    pageLoadTimeout="00:01:30" >
        <settings>
          <add name="RemoteUrl" value="http://selenium.ourinternalserver.com:4444/wd/hub"/>
        </settings>
      </browserFactory>
    </specBind>

This has been working great, but sometimes the site is slow to start up on first and is causing timeouts for the first request. 

We see the following error: 

-> error: Errors occurred while entering data. Details: The HTTP request to the remote WebDriver server for URL http://selenium.office.ourdomainhere.co.uk:4444/wd/hub/session/fa52b151-fe6c-4ad3-901d-1def0b93bd21/element timed out after 60 seconds.; The HTTP request to the remote WebDriver server for URL http://selenium.office.ourdomainhere.co.uk:4444/wd/hub/session/fa52b151-fe6c-4ad3-901d-1def0b93bd21/element timed out after 60 seconds.; The HTTP request to the remote WebDriver server for URL http://selenium.office.ourdomainhere.co.uk:4444/wd/hub/session/fa52b151-fe6c-4ad3-901d-1def0b93bd21/element timed out after 60 seconds.

Shouldn't the pageLoadTimeout setting be applied here, or does this not work for remote webdriver? Is there another setting i've missed somewhere?

Thanks,
Rob

**Comment by dpiessens** [comment]
I did some digging into the Selenium driver and I couldn't find any documentation on a setting to propagate this through the remote driver. If you can find a remote setting I can pass, I'll modify SpecBind to set it up on the remote driver.

**Comment by EricBlack** [comment]
Hi, I also got this issue when doing automation testing with C#, if there any workaround or new progress to resolve this issue?
