### ISSUE TITLE
Documentation: Withing With Lists

### ISSUE THREAD

**Issue by RefuX** [dpiessens/specbind#59]
Hi there, looking at document:
https://github.com/dpiessens/specbind/wiki/Working-With-Lists

It is a fantastic issue expect it doesn't show what the .feature file should look like. So I am struggling with that.

**Comment by scottcowan** [comment]
Hi Refux,

Here's some links that should help
* [Validating Lists](https://github.com/dpiessens/specbind/wiki/Verifying-Steps#validating-lists)
* [At the bottom you'll find examples on how to wait on lists](https://github.com/dpiessens/specbind/wiki/Waiting-Steps)

Scott
