### ISSUE TITLE
Setting a cookie for a page

### ISSUE THREAD

**Issue by scottcowan** [dpiessens/specbind#60]
I would like to specify that a cookie for a page when it is navigated to

```c#
[PageNavigation]
[SetCookie(name,value,expire,path,domain,secure,httponly)]
public class MyPage{}
```

There might be a better way to do this, I haven't had a chance to look too deeply into this.

Reason:
I have a disclaimer popup that I want to avoid by setting a cookie

Thanks again

**Comment by scottcowan** [comment]
If I added a cookie in the page constructor will that be too late. 

Should I look at adding a hook to have access to the browser earlier?

**Comment by dpiessens** [comment]
Sorry didn't mean to add the won't fix label. I I think we can add a pre-action to the navigation action, but we'll have to add something to the IBrowser interface to add the cookie, and then use the pre-action to discover the attribute. This is a good enhancement, I'll take a look at what would go into it.

**Comment by dpiessens** [comment]
FYI it looks like the only thing I can't support is HttpOnly as that works by embedding the cookie in the HTML. Also Selenium doesn't support secure mode through the API. I've added the code for the browser support, I'll add the attribute and pre-step soon.

**Comment by dpiessens** [comment]
I'll release this with the 1.5 update, there's a few other issues I want to see if we should address in this release.
