### ISSUE TITLE
Enhancement to allow checking the number of items in a list

### ISSUE THREAD

**Issue by JohnGrekso** [dpiessens/specbind#61]
We have a number of pages on our site that implement an infinite scrolling mechanism.  To validate this we will navigate to the page, check the number of items in the list, page down and then check the number of lists again.  This method has been working for us but we have to create custom steps to check the number of items in each list we do this in.  An example of the step we implement is below.

    [Given(@"the student list contains (.*) items")]
    [Then(@"the student list contains (.*) items")]
    public void ValidateStudentListRowCount(int resultCount)
    {
    	var basePage = GetPageFromContext();
    	var actualPage = basePage.GetNativePage<StudentListPage>();
    	Assert.AreEqual(resultCount, actualPage.StudentList.Count());
    }

Is this already supported and I just don't know it?  If not, would adding a generic step such as this to SpecBind make sense?

**Comment by dpiessens** [comment]
Hi John, I think this makes sense to have as a generic step, we'll start with a contains action but I could see at least or at most also being valuable.

**Comment by JohnGrekso** [comment]
I would agree that an __at least__ or __at most__ could be beneficial actions as well for this step.

**Comment by dpiessens** [comment]
Added at least and at most as well as exactly for the current use case.
