### ISSUE TITLE
Expected "http://localhost:xxxxx"; Actual: about:blank

### ISSUE THREAD

**Issue by fourpastmidnight** [dpiessens/specbind#64]
# Problem Statement

So, this is my first time using SpecBind. I read all the documentation, looked at the examples in the documentation and the full sample used here at the site, and finally proceeded to write my first feature spec that simply navigates to the Home page of a new ASP.Net MVC project and find the DIV element whose class attribute equals `jumbotron`. That's it. Very simple. But, it doesn't work. 
## Problem Setup

Below is the code in the test project that was used to produce the behavior.

**HomePage.cs**

``` csharp
[PageNavigation("/")]
public class HomePage : HtmlDocument
{
    public HomePage(UITestControl parent) : base(parent) { }

    [ElementLocator(Class = "jumbotron")]
    public HtmlDiv Jumbotron { get; set; }
}
```

**UnderstandingSpecBind.feature**

``` gherkin
Feature: UnderstandingSpecBind
    In order to understand how SpecBind works
    As a developer
    I want to test that I can find the <div class='jumbotron'> element on the Home page.

Scenario: Find the HTML element '<div class="jumbotron">' element on the Home page.
    Given I navigated to the {Home} page
    When I am on the {Home} page
    Then there should be a div whose class attribute is jumbotron
```

**StepDefinitions/UnderstandingSpecBind.cs**

``` csharp
[Binding]
public sealed class UnderstandingSpecBind
{
    [Then(@"there should be a div whose class attribute is jumbotron")]
    public void ThenThereShouldBeADivWhoseClassAttributeIsJumbotron()
    {
        ScenarioContext.Current.Pending();
    }
}
```
## What I Expected to Happen

I expected that the **Given** step would navigate the browser to the site's home page. After reading the SpecBind documentation, I understand that these steps use the past tense to signify that, to the reader's perspective, the action has already occurred. Accordingly, the browser navigates to my sites' home page.

I then expected that a verification (i.e. some sort of assertion) would occur to ensure that I am actually on my site's Home page when the **When** step executes.

Finally, I expected that I would get an inconclusive result for the **Then** step since I hadn't provided a definition for that step yet.
## What Actually Happened

The test failed while processing the **When** step. Here's the output from the test runner:

``` text
Test Failed - FindTheHTMLElementDivClassJumbotronOnTheHomePage_
Message: Test method UnderstandingSpecBindFeature.FindTheHTMLElementDivClassJumbotronOnTheHomePage_ throw exception:
SpecBind.Pages.PageNavigationException: Cannot navigate to HomePage, Url: http://localhost:14512/, Actual: about:blank
```

If I comment out the **When** step in my feature file and re-run the test, then "it passes" (actually, it's inconculsive because of the `ScenarioContext.Current.Pending();` in my **Then** step definition, but that's what I originally expected to occur as specified above).
## Additional Findings

I know that for SpecFlow (or should I say Gherkin), **Given** and **When** are just keywords to help the Gherkin parser--it doesn't matter which order they appear in. So I thought, what if I omit the **Given** step in my feature file above, and only use the **When** step:

``` gherkin
When I am on the {Home} page
Then there should be a div whose class attribute is jumbotron
```

After running this, however, the test fails again with a similar failure as above, but slightly different enough to make me think there may be a bug in the **When** step definition:

``` text
Test Failed - FindTheHTMLElementDivClassJumbotronOnTheHomePage_
Message: Test method UnderstandingSpecBindFeature.FindTheHTMLElementDivClassJumbotronOnTheHomePage_ throw exception:
SpecBind.Pages.PageNavigationException: Cannot navigate to HomePage, Url: http://localhost:14512/, Actual: http://www.msn.com/
```

Notice this time the **Actual** argument value: the home page I currently have set for Internet Explorer (not `about:blank` as in my original test with both a **Given** and **When**). In the test above, should I have expected it to fail, I would have expected it to fail in the same exact way. So why is the behavior different?

**Comment by fourpastmidnight** [comment]
Took a look in the source code for the **Given** and **When** steps in question.

Firstly, I noticed that the same method is used for both `Given I navigated to the (.+) page` and `When I navigate to the (.+) page` steps. The method causes the browser to navigate to the requested page. Given the example feature file in my original issue post above, I would expect that the browser would, upon executing the **Given** step, navigate to the specified page, which it does. Then I would expect that the **When** step would navigate to the same page again, but it doesn't--or, at least, it tries, but the browser's location becomes `about:blank` instead of the expected page.

Even though I realize now that I don't need to specify both the **Given** and **When** steps that I have in my feature file, it still should have worked, even if its inefficient.

**Comment by dpiessens** [comment]
Hi, thanks for the really complete report! I know we fixed a bug in the past with navigation in the page, but it's a little difficult to tell if the navigation step is the problem. Here's a few things you can try:

(this won't fix it but it will complete your final step without code)
```gherkin
Then I see
         | Field     | Rule   | Value   |
         | Jumbotron | exists | true    |
```

The navigation code is optimized to no re-run navigation if it thinks it's already on that page which it may be doing incorrectly at this point. The way to check this is to add an appsetting to print out additional debug logging while running. Add this to the scenario and run it again. In the test output you should see what page it expects to be on and what the actual is:

```xml
<specflow>
   (other xml here)
   <trace traceSuccessfulSteps="true"/>
</specflow>
```

**Comment by fourpastmidnight** [comment]
@dpiessens Thanks for the tip on the **Then** step!! Also, I think it's great that SpecBind tries to optimize unnecessary navigation. What's troubling, however, is that in my original spec with the Given, When, and Then steps, after executing the **When** step, the browser location appears (to the test runner) to be `about:blank` (the location shown in the browser itself did not change). Also, the fact that these two specs are not equivalent (when, by looking at the code it appears they should be) is a bit concerning, too:

```gherkin
Given I have navigated to the {Home} page
Then I see
    | Field     | Rule   | Value |
    | Jumbotron | exists | true  |

# The test below is not equivalent to the one above; in fact, it fails!! Is this expected behavior?
When I navigate to the {Home} page
Then I see
    | Field     | Rule   | Value |
    | Jumbotron | exists | true  |
```

I should mention that the browser in use during these tests was IE11 with latest updates (since I was using the CodedUITest SpecBind extension). I didn't try these tests using a different browser with the Selenium Web Driver extension for SpecBind.

**Comment by dpiessens** [comment]
I haven't tried any debugging with IE11 so that could be the problem. I'm also not sure is MS has tested all this yet as it's had bugs with CodedUI and new browsers in the past. If I have some time I'll run some tests.

**Comment by fourpastmidnight** [comment]
Ah, I hadn't heard the Coded UI Test Tools were buggy. IE11 is supposedly supported by them according to MSDN; and, browsers change so fast, I can only imagine how hard it is to make sure testing against the "latest" is anything but easy. Heck, even MS doesn't release updates for CodedUITests for the latest versions of FF and Chrome that seem to ship nearly every other week.

If I get some time, I'll fork this project and see if I can find anything that may be causing this behavior.

Thanks again for the replies.

**Comment by icnocop** [comment]
I think you're just missing the `startUrl` in your `app.config` as documented in [Configuration](https://github.com/dpiessens/specbind/wiki/Configuration).
For example:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
  <section name="specBind" type="SpecBind.Configuration.ConfigurationSectionHandler, SpecBind" />
  <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow" />
</configSections>
  <specFlow>
    <stepAssemblies>
      <stepAssembly assembly="SpecBind" />
    </stepAssemblies>
    <plugins>
      <add name="SpecBindGeneratorPlugin" type="Generator" />
    </plugins>
    <unitTestProvider name="MsTest" />
  </specFlow>
  <specBind>
    <browserFactory provider="SpecBind.CodedUI.CodedUIBrowserFactory, SpecBind.CodedUI" browserType="IE" />
    <application startUrl="http://localhost/MyAspNetWebSite" />
  </specBind>
</configuration>
```
