### ISSUE TITLE
Inclusion/Exclusion list for scanned assemblies

### ISSUE THREAD

**Issue by NickMcG** [dpiessens/specbind#67]
SpecBind (specifically, ActionRepository) is scanning my loaded assemblies and is causing stuff to blowup because it is interacting with classes that don't have their dependencies loaded yet. After spending several hours trying to figure out the issue, I put a quick hack in place where it will exclude a specific DLL. This quick hack fixes my issue.

What would you think about adding an inclusion and/or an exclusion list for which assemblies to scan? If neither are provided, it scans all assemblies; otherwise it will only scan the inclusion assemblies or skip over the exclusion assemblies?

I'm hoping to have a pull request available tomorrow of what I'm thinking.

**Comment by dpiessens** [comment]
Added in version 1.5.3
