### ISSUE TITLE
Waiting for navigation after clicking a button

### ISSUE THREAD

**Issue by robertbird** [dpiessens/specbind#72]
I'm trying to write a test for a login page. 

After entering the username & password I click the login button and want to assert the fact that I have been taken to a dashboard page. I have the following feature file:

    Scenario: Login in as an administrator
	Given I navigated to the Login page
	When I enter data 
		| Field        | Value                     |
		| User Name    | admin@site.com |
		| Password     | myPassword123 |
	And I choose Login
	Then I am on the Dashboard page

But I am getting an error saying that the URL doesn't match because when the assertion fires it is still in the middle of navigating away from the login page. So it is checking the login URL against the Dashboard URL

What is the recommended way to wait for the navigation to happen?

Thanks in advance,
Rob

**Comment by dpiessens** [comment]
You can use
* I wait for the Dashboard page
* I wait 10 seconds for the Dashboard page

For the view to transition. Sorry I never added those steps to the wiki but they are useful for these types of pages.

**Comment by robertbird** [comment]
Thank you! That was perfect and worked like a charm, 

I can't believe I missed that. Thanks for helping.

Rob
