### ISSUE TITLE
Stale element exception during 'wait to not see... ' steps

### ISSUE THREAD

**Issue by BrianSkibinski** [dpiessens/specbind#74]
Hello,

We have a situation in which a dialog appears on the page, we verify some stuff on it, and then when action is taken it disappears when the save succeeds.  We are trying to figure out how to wait until it disappears before navigating to another page.

For example:
When I wait for the modal dialog to appear
and I click the submit button
and I wait 5 seconds to not see the modal dialog.  <--- this throws StaleElementReferenceException

Looking through code, it looks like because the dialog was there, it's cached and then when it disappears it doesn't clear that cache, so the cached element is stale and the various NotFound catches in the CheckElementState function in SeleniumPage.cs handler don't catch it.

I'm thinking it's as easy as adding staleelementexception as another catch in that method, but wanted to get your thoughts before submitting a pull request for it.  I also haven't really thought about what catching a stale element exception there would mean for the other checks that use that shared method.

Anyway, just wanted to get your thoughts on the fix before submitting a pull request.  Thanks!

**Comment by dpiessens** [comment]
I believe this would be the way to resolve this. If you're interesting in submitting a PR please do so!
