### ISSUE TITLE
Clear data on a field

### ISSUE THREAD

**Issue by adback03** [dpiessens/specbind#76]
Some fields on a webpage have a default value, and using the "enter data" step, the data just gets appended to the current value. Is there anyway to overwrite the entire value of the field by setting the text directly or clearing its contents before sending key strokes?

**Comment by NickMcG** [comment]
I am also running into this issue. I have some numeric fields that are defaulting to "0.00" (to show the user the expected format), but when I enter data, it adds to the front of it (i.e., adding 1.5 results in the text box now having "1.50.00").

I was thinking of making a step "Given I cleared data / When I clear data / Then I clear data", following the pattern of EnterDataAction.

**Comment by dpiessens** [comment]
@NickMcG was kind enough to submit a fix, this will be published in 1.5.5 out shortly.
