### ISSUE TITLE
SpecFlow 2.0 Compatability

### ISSUE THREAD

**Issue by cable729** [dpiessens/specbind#86]
It seems like SpecBind wants SpecFlow >= 1.9.0 and SpecBindGeneratorPlugin.SpecFlow wants SpecFlow = 1.9.0.

```
PM> Install-Package SpecBind.CodedUI
Attempting to gather dependencies information for package 'SpecBind.CodedUI.1.6.0.219' with respect to project 'Tests\WebPortal.Specs', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'SpecBind.CodedUI.1.6.0.219' with DependencyBehavior 'Lowest'
Install-Package : Unable to resolve dependencies. 'SpecFlow 2.0.0' is not compatible with 'SpecBind 1.6.0.219 constraint: SpecFlow (≥ 1.9.0)', 'SpecBindGeneratorPlugin.SpecFlow 1.6.0.219 constraint: SpecFlow (= 1.9.0)', 'SpecFlow.xUnit 2.0.0 constraint: SpecFlow (= 2.0.0)'.
At line:1 char:1
+ Install-Package SpecBind.CodedUI
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
```

**Comment by NickMcG** [comment]
Unfortunately, SpecFlow 2.0.0 requires a bit of an update. Some of the pieces that were baked into TechTalk.SpecFlow.dll have been refactored out into separate assemblies (looks like maybe Gherkin.dll and TechTalk.SpecFlow.Generator.dll?), and the use of the static context properties is deprecated (or at least not preferred if you want to run tests concurrently). I also had trouble regenerating the feature files until I updated my Visual Studio SpecFlow extension.

I have a branch that is updated to use SpecFlow 2.0.0 at https://github.com/NickMcG/specbind/tree/specflow-2-support.

Whenever we are ready to make that jump, I can submit a pull request with my changes.

**Comment by dpiessens** [comment]
I'd love to tackle this one soon. I have an open branch on updating to VS 2015, .NET 4.5.2 and get rid of StyleCop for some inspectors. The inspectors have been taking the most time but should be done soon. I'd prefer to do the update after that but if you'd prefer to do it now let me know.

**Comment by NickMcG** [comment]
That works for me. I was mainly seeing what level of effort it would take to get tests running in parallel. Let me know if you would like any help with it.
