### ISSUE TITLE
Edge Support?

### ISSUE THREAD

**Issue by NickMcG** [dpiessens/specbind#88]
Edge is not listed in the BrowserType enumeration (https://github.com/dpiessens/specbind/blob/master/src/SpecBind/BrowserSupport/BrowserType.cs). It looks like the is a specific Selenium driver for Edge (https://msdn.microsoft.com/en-us/library/mt188085(v=vs.85).aspx).

Does SpecBind currently support Edge? I honestly haven't tried, but looking through the code, I would guess that it doesn't.

Would the steps to adding Edge support be:
1. Add Edge to the BrowserType enum
2. Add an Edge case to the CodedUIBrowserFactory (just setting browserKey to "edge"?)
3. Add a DownloadEdgeDriver function to SeleniumBrowserFactory, along with an Edge case in CreateWebDriver
?

(Plus all of the testing required, of course.)

**Comment by dpiessens** [comment]
I think you're correct with all of that, we would also need to check if there's a new enum in MSTest for Edge as well.
